# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articledownload',
            options={'managed': False, 'verbose_name': 'Article Download'},
        ),
    ]
