# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0002_auto_20170127_1256'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articledownload',
            table='Article_Download',
        ),
    ]
