# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0003_auto_20170127_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecontent',
            options={'managed': False, 'verbose_name': 'Article Content'},
        ),
        migrations.AlterModelOptions(
            name='articleparsed',
            options={'managed': False, 'verbose_name': 'Article Parsed'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'managed': False, 'verbose_name': 'Author'},
        ),
        migrations.AlterModelOptions(
            name='mapunresolvedresolvedlocation',
            options={'managed': False, 'verbose_name': 'Map Unresolved Resolved Location'},
        ),
        migrations.AlterModelOptions(
            name='mapunresolvedresolvednewstype',
            options={'managed': False, 'verbose_name': 'Map Unresolved Resolved News Type'},
        ),
        migrations.AlterModelOptions(
            name='resolvedlocation',
            options={'managed': False, 'verbose_name': 'Resolved Location'},
        ),
        migrations.AlterModelOptions(
            name='resolvednewstype',
            options={'managed': False, 'verbose_name': 'Resolved News Type'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'managed': False, 'verbose_name': 'Source'},
        ),
        migrations.AlterModelOptions(
            name='unresolvedlocation',
            options={'managed': False, 'verbose_name': 'UnResolved Location'},
        ),
        migrations.AlterModelOptions(
            name='unresolvednewstype',
            options={'managed': False, 'verbose_name': 'UnResolved News Type'},
        ),
        migrations.AlterModelTable(
            name='articledownload',
            table='ArticleDownload',
        ),
    ]
