# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0005_auto_20170130_0552'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resolvednewstype',
            table='ResolvedNewsType',
        ),
    ]
