# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0007_auto_20170131_1015'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resolvednewstype',
            table='ResolvedNews_Type',
        ),
    ]
