# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0008_auto_20170131_1018'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resolvednewstype',
            table='rest',
        ),
    ]
