# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0009_auto_20170131_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resolvednewstype',
            options={'verbose_name': 'Resolved News Type'},
        ),
    ]
