# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0010_auto_20170131_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resolvednewstype',
            options={'managed': False, 'verbose_name': 'Resolved News Type'},
        ),
    ]
