# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdb', '0011_auto_20170201_0446'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecontent',
            table='article_content',
        ),
        migrations.AlterModelTable(
            name='articledownload',
            table='article_download',
        ),
        migrations.AlterModelTable(
            name='articleparsed',
            table='article_parsed',
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='mapunresolvedresolvedlocation',
            table='map_unresolved_resolved_location',
        ),
        migrations.AlterModelTable(
            name='mapunresolvedresolvednewstype',
            table='map_unresolved_resolved_news_type',
        ),
        migrations.AlterModelTable(
            name='resolvedlocation',
            table='resolved_location',
        ),
        migrations.AlterModelTable(
            name='resolvednewstype',
            table='resolved_news_type',
        ),
        migrations.AlterModelTable(
            name='source',
            table='source',
        ),
        migrations.AlterModelTable(
            name='unresolvedlocation',
            table='unresolved_location',
        ),
        migrations.AlterModelTable(
            name='unresolvednewstype',
            table='unresolved_news_type',
        ),
    ]
